### ISSUE TITLE
Write valid tests for functions that add todo list items

### ISSUE THREAD

**Issue by jackherizsmith** [fac19/week3-JICG#14]
This is to ensure our tests are passing as we continue to develop the site

- [ ] can the user input an item
- [ ] the submit button does not do anything if there is no text in the input field
- [ ] when you press the submit button a new todo appears on the end of the list
- [ ] input field should return to blank after item is added
